import React,{useEffect,useState}from'react';import{Table,Button,Space,Tag,Modal,Form,Input,Popconfirm,message,InputNumber}from'antd';import{PlusOutlined,EditOutlined,DeleteOutlined}from'@ant-design/icons';import request from'../api/request';
interface Topic{id:number;name:string;description:string;noteCount:number;followCount:number;status:number}
const TopicList:React.FC=()=>{const[data,setData]=useState<Topic[]>([]);const[loading,setLoading]=useState(false);const[modalOpen,setModalOpen]=useState(false);const[editing,setEditing]=useState<Topic|null>(null);const[saving,setSaving]=useState(false);const[form]=Form.useForm();
const fetch=()=>{setLoading(true);request.get('/topic/admin/list').then((r:any)=>{if(r.success)setData(r.data||[])}).catch(()=>{}).finally(()=>setLoading(false));};
useEffect(()=>{fetch();},[]);
const save=async()=>{try{const v=await form.validateFields();setSaving(true);if(editing){await request.put('/topic/update',{...v,id:editing.id});message.success('已更新');}else{await request.post('/topic/create',v);message.success('已创建');}setModalOpen(false);fetch();}catch(e:any){if(!e?.errorFields)message.error('保存失败');}finally{setSaving(false);}};
const del=async(id:number)=>{await request.delete('/topic/delete',{params:{id}});message.success('已删除');fetch();};
const columns=[{title:'ID',dataIndex:'id',width:50},{title:'话题名',dataIndex:'name'},{title:'描述',dataIndex:'description',ellipsis:true},{title:'游记数',dataIndex:'noteCount',width:70},{title:'关注',dataIndex:'followCount',width:70},{title:'状态',dataIndex:'status',width:60,render:(v:number)=><Tag color={v===1?'green':'red'}>{v===1?'启用':'禁用'}</Tag>},{title:'操作',width:160,render:(_:any,r:Topic)=>(<Space size="small"><Button size="small" icon={<EditOutlined/>} onClick={()=>{setEditing(r);form.setFieldsValue(r);setModalOpen(true);}}>编辑</Button><Popconfirm title="确定删除？" onConfirm={()=>del(r.id)}><Button size="small" danger icon={<DeleteOutlined/>}>删除</Button></Popconfirm></Space>)}];
return(<div><div style={{display:'flex',justifyContent:'space-between',marginBottom:16}}><h2>话题管理</h2><Button type="primary" icon={<PlusOutlined/>} onClick={()=>{setEditing(null);form.resetFields();form.setFieldsValue({status:1});setModalOpen(true);}}>新增话题</Button></div><Table columns={columns} dataSource={data} loading={loading} rowKey="id" size="middle"/><Modal title={editing?'编辑':'新增'} open={modalOpen} onCancel={()=>setModalOpen(false)} onOk={save} confirmLoading={saving}><Form form={form} layout="vertical" style={{marginTop:16}}><Form.Item name="name" label="话题名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="description" label="描述"><Input.TextArea rows={2}/></Form.Item><Form.Item name="status" label="状态"><Input.Group compact><Button type={form.getFieldValue('status')===1?'primary':'default'} onClick={()=>form.setFieldsValue({status:1})}>启用</Button><Button type={form.getFieldValue('status')===0?'primary':'default'} onClick={()=>form.setFieldsValue({status:0})}>禁用</Button></Input.Group></Form.Item></Form></Modal></div>);};
export default TopicList;
