import { Provide } from '@midwayjs/core'; import { InjectEntityModel } from '@midwayjs/typeorm'; import { Repository } from 'typeorm'; import { ProductReview } from '../entity/product-review.entity'; import { IPageParams, IPageResult } from '../interface';
@Provide() export class HomestayReviewService {
  @InjectEntityModel(ProductReview) model: Repository<ProductReview>;
  async listByHomestay(hid:number,page=1,pageSize=20):Promise<IPageResult<ProductReview>>{const qb=this.model.createQueryBuilder('r').where('r.is_deleted=0').andWhere('r.homestay_id=:hid',{hid}).andWhere('r.status=1');const[l,t]=await qb.skip((page-1)*pageSize).take(pageSize).orderBy('r.created_at','DESC').getManyAndCount();return{list:l,total:t,page,pageSize};}
  async adminList(params:IPageParams & {homestayId?:number;status?:number}):Promise<IPageResult<ProductReview>>{const{page=1,pageSize=10,homestayId,status}=params;const qb=this.model.createQueryBuilder('r').where('r.is_deleted=0').andWhere('r.homestay_id IS NOT NULL');if(homestayId)qb.andWhere('r.homestay_id=:hid',{hid:homestayId});if(status!==undefined&&status!==null)qb.andWhere('r.status=:st',{st:status});const[l,t]=await qb.skip((page-1)*pageSize).take(pageSize).orderBy('r.created_at','DESC').getManyAndCount();return{list:l,total:t,page,pageSize};}
  async create(data:Partial<ProductReview>):Promise<ProductReview>{const r=new ProductReview();Object.assign(r,data);r.status=1;return this.model.save(r);}
  async reply(id:number,reply:string):Promise<ProductReview|null>{const r=await this.model.createQueryBuilder('r').where('r.id=:id',{id}).getOne();if(!r)return null;r.reply=reply;return this.model.save(r);}
  async updateStatus(id:number,status:number):Promise<ProductReview|null>{const r=await this.model.createQueryBuilder('r').where('r.id=:id',{id}).getOne();if(!r)return null;r.status=status;return this.model.save(r);}
}
